version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: partitioned-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: partitioned_db
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./entrypoint:/entrypoint
      - ./scripts:/scripts
    command: [ "bash", "/entrypoint/start.sh" ]
    ports:
      - "5432:5432"

volumes:
  pgdata:
